/*
OPERADORES DE COMPARAÇÃO

> MAIOR QUE 
>= MAIOR QUE OU IGUAL A 
< MENOR QUE 
<= MENOR QUE OU IGUAL A
== IGUALDADE (VALOR) (= É ATRIBUIÇÃO)
=== IGUALDADE ESTRITA (VALOR E TIPO)
!= DIFERENTE (VALOR)
!== DIFERENTE ESTRITO (VALOR E TIPO)

*/
